name: PR comparison

on:
  issue_comment:
    types: [created, edited]

jobs:
  compare:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@github-actions eslint-remote-tester compare')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.11
      - run: yarn install
      - uses: AriPerkkio/eslint-remote-tester-compare-action@fix/event-check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
