name: PR comparison

on:
  issue_comment:
    types: [created, edited]

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.11
      - run: yarn install
      - run: node ci/getPullRequestsRepository.js
        id: getPrBranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: node ci/index.js
      - run: node ci/saveCache.js
      - uses: actions/checkout@v2
        with:
          repository: ${{ steps.getPrBranch.outputs.repository }}
          ref: ${{ steps.getPrBranch.outputs.branch }}
      - run: node ci/restoreCache.js
      - run: node ci/index.js
