name: PR comparison

on:
  issue_comment:
    types: [created, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.11
      - run: yarn install
      - run: node ci/index.js
