name: Smoke test

on:
  workflow_dispatch:
  schedule:
    # Every thursday at 00:00
    - cron: "0 00 * * THU"

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.11
      - run: yarn install
      - uses: AriPerkkio/eslint-remote-tester-run-action@fix/node-version
        with:
          issue-title: "Results of weekly scheduled smoke test"
          eslint-remote-tester-config: eslint-remote-tester.config smoke.js
          max-result-count: 2
