name: Smoke test

on:
  workflow_dispatch:
  schedule:
    # Every thursday at 00:00
    - cron: "0 00 * * THU"

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.11
      - uses: AriPerkkio/eslint-remote-tester-run-action@feat/initial
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
