name: Smoke test typescript

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: pnpm install

      - uses: AriPerkkio/eslint-remote-tester-run-action@master
        with:
          issue-title: "Results of weekly scheduled smoke test"
          eslint-remote-tester-config: eslint-remote-tester.typescript.config.ts
